### ISSUE TITLE
Naming our files and folders.

### ISSUE THREAD

**Issue by FarahZaqout** [FACG4/mwb#20]
The names of our files and folders should be consistent to prevent any unintended problems. There are many ways to name files and folders, personally I prefer the format file_name.ext, but you guys may disagree. I suggest we decide in this issue how the naming format is going to work.

**Comment by IsraaMoqbel** [comment]
I suggest capital letters instead of underscore _

**Comment by FarahZaqout** [comment]
As you guys suggested, all files and folders would be named with the camelcase format (fileName.ext)
