### ISSUE TITLE
Assigning Issues and teamwork

### ISSUE THREAD

**Issue by FarahZaqout** [FACG4/mwb#29]
Hey, everyone. I was looking at the issues and how we assign ourselves, and it was a little confusing.
I am still not able to understand how much progress we have made by looking at them.

I think the proper way is to assign ourselves to one issue only, once pushed we can start thinking about the other issues, but I don't believe it would be appropriate to start on a second issue when the first has yet to be approved and merged.

This might be slower at first but I think it would be smoother in the long run.

What do you think?

**Comment by sallamTanna** [comment]
Right!
on Sunday me and Israa will modify the assignment, so everything will be more clear for all!

**Comment by FarahZaqout** [comment]
Great! Thank you.
